security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            stateless: true
            provider: app_user_provider
            jwt:
                auth_checker: lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        # Rota de login aberta
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # Proteja rotas da API
        - { path: ^/api, roles: ROLE_USER }
